version: 2.1

orbs:
  node: circleci/node@2.1.0
  sonarcloud: sonarsource/sonarcloud@1.0.1

parameters:
  node-version:
    type: string
    default: "12.16"

# Require environment data
# you can see all require environment variable at .env-default file

commands:
  gpg-setup:
    description: GPG setup
    steps:
      - run:
          name: "Import private key in GPG"
          command: echo "$GPG_PRIVATE_KEY_BASE64" | base64 --decode | gpg --batch --allow-secret-key-import --import
  gpg-cleanup:
    description: GPG cleanup
    steps:
      - run:
          name: "Deleting private key in GPG"
          command: gpg --batch --yes --delete-secret-key "$GPG_IDENTIFY_KEY"
      - run:
          name: "Deleting public key in GPG"
          command: gpg --batch --yes --delete-key "$GPG_IDENTIFY_KEY"
      - run:
          name: "Listing all secret keys in GPG"
          command: gpg --keyid-format LONG --list-secret-key
  git-setup:
    description: Git setup
    steps:
      - run:
          name: "Add git user email"
          command: git config --global user.email "$COMMIT_EMAIL"
      - run:
          name: "Add git username"
          command: git config --global user.name "$COMMIT_NAME"
      - run:
          name: "Add git user signing key"
          command: git config --global user.signingKey "$GPG_SIGNING_KEY"
  git-cleanup:
    description: Git cleanup
    steps:
      - run:
          name: "Add git user email"
          command: git config --global user.email "user@example.com"
      - run:
          name: "Add git username"
          command: git config --global user.name "example user"
      - run:
          name: "Add git user signing key"
          command: git config --global user.signingKey "abc"
  install-aptget:
    description: Install aptget package
    parameters:
      package-name:
        description: aptget package name
        type: string
    steps:
      - run:
          name: Install << parameters.package-name >>
          command: |
            sudo add-apt-repository universe
            sudo apt-get update
            sudo apt-get install -y << parameters.package-name >>
  install-dependencies:
    description: Install and links projects
    parameters:
      only-lerna:
        default: false
        type: boolean
        description: only install lerna
    steps:
      - node/install-packages:
          cache-version: "v1-lerna"
          cache-key: "yarn.lock"
          pkg-manager: yarn
          include-branch-in-cache-key: false
      - unless:
          condition: << parameters.only-lerna >>
          steps:
            - run:
                name: Install and links lerna project together
                command: yarn bootstrap
  publish:
    description: Publish new version
    parameters:
      option:
        description: extra option for version command
        type: string
    steps:
      - run:
          name: "Update version on package"
          command: yarn version:ci << parameters.option >> || true
      - run:
          name: "Release new package version"
          command: yarn release:ci || true

jobs:
  main:
    docker:
      - image: cimg/node:<< pipeline.parameters.node-version >>
    environment:
      ENV: "ci"
      JEST_JUNIT_OUTPUT_DIR: ./reports/junit/
    steps:
      - checkout
      - install-dependencies
      - run:
          name: "Compile and build application"
          command: yarn build:ci
      - run:
          name: "Test all unittest"
          command: yarn test:ci
      - sonarcloud/scan:
          cache_version: 1
      - store_test_results:
          path: ./reports/junit/
      - store_artifacts:
          path: ./coverage
          destination: reports/coverage
      - store_artifacts:
          path: ./reports/junit/
          destination: reports/junit

  build-graph:
    docker:
      - image: cimg/node:<< pipeline.parameters.node-version >>
    steps:
      - checkout
      - install-aptget:
          package-name: graphviz
      - install-dependencies
      - run:
          name: Build compiler
          command: yarn build:init
      - run:
          name: Build internal graph generator
          command: yarn build:graph
      - run:
          name: "Build dependencies graph"
          command: yarn start:graph
      - store_artifacts:
          path: ./internals/graph/graph.pdf
          destination: result/graph.pdf

  release-beta:
    docker:
      - image: cimg/node:<< pipeline.parameters.node-version >>
    steps:
      - checkout
      - gpg-setup
      - git-setup
      - install-dependencies:
          only-lerna: true
      - publish:
          option: "type=beta"
      - git-cleanup
      - gpg-cleanup

  release-rc:
    docker:
      - image: cimg/node:<< pipeline.parameters.node-version >>
    steps:
      - checkout
      - gpg-setup
      - git-setup
      - install-dependencies:
          only-lerna: true
      - publish:
          option: "type=rc"
      - git-cleanup
      - gpg-cleanup

  release:
    docker:
      - image: cimg/node:<< pipeline.parameters.node-version >>
    steps:
      - checkout
      - gpg-setup
      - git-setup
      - install-dependencies:
          only-lerna: true
      - publish:
          option: ""
      - git-cleanup
      - gpg-cleanup

workflows:
  version: 2
  default:
    jobs:
      - main:
          context: monots-release
      - build-graph:
          filters:
            branches:
              only:
                - master
          requires:
            - main
      - release:
          context: monots-release
          filters:
            branches:
              only:
                - master
          requires:
            - build-graph
      - release-rc:
          context: monots-release
          filters:
            branches:
              only:
                - develop
          requires:
            - main
      - release-beta:
          context: monots-release
          filters:
            branches:
              only:
                - /feature\/.*/
          requires:
            - main
